import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';

part 'isar_service.g.dart'; // Will be generated by build_runner

@Collection()
class Blog {
  Id? id; // Isar will automatically assign an ID
  String? title;
  String? content;
  DateTime? createdAt;
}

class IsarService {
  static Isar? _isar;

  static Future<Isar> get instance async {
    if (_isar != null) {
      return _isar!;
    }
    final dir = await getApplicationDocumentsDirectory();
    _isar = await Isar.open(
      [BlogSchema], // Ganti dengan skema yang sesuai
      directory: dir.path,
    );
    return _isar!;
  }
}
